# Generated by Django 4.0.6 on 2023-01-06 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_farmonlar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biz_haqimizda',
            old_name='img_1',
            new_name='img',
        ),
        migrations.RemoveField(
            model_name='biz_haqimizda',
            name='img_2',
        ),
    ]
